//! Declarative axis → inner-tool flag mapping (§13.6).
//!
//! A rule that wraps a flag-based tool (cargo today; future cc/go/swift/…) declares, per
//! configuration [`Axis`] it cares about, how that axis's value renders into one of the
//! tool's flag *sinks* (an env var like `RUSTFLAGS` today). The framework reads this single
//! declaration to BOTH render the flags for a node's configuration AND derive the action's
//! `consumed_axes` — so the "I mapped an axis to a flag but forgot to consume it ⇒ stale
//! cache" hazard is structurally closed: an axis in the map is, by construction, consumed.
//!
//! **The tag and the value are bound by the type system.** Each axis has its own builder
//! method ([`AxisFlagMap::lto`], …, generated by `axis_flag_methods!`) whose renderer takes
//! *only that axis's value* (`fn(Lto) -> Option<String>`), not the whole [`AxisValues`]. So a
//! renderer physically cannot read a different axis: the consumed set (from the tags) and the
//! renderers' real dependencies are guaranteed equal. The method also owns the field
//! extraction, so there is no hand-written `(tag, field)` pairing a rule could mismatch.
//!
//! The flag *spelling* stays the rule's knowledge (the opaque-engine boundary, §3.2): the
//! framework only calls the rule's render `fn` and routes the resulting string — it never
//! parses or interprets it. Axes whose effect is *not* a textual flag (cargo's `opt_level`
//! → `--release` + output dir; `exec_mode` → a state grant) are simply left out of the map;
//! a rule consumes those explicitly via [`configure_axis_action`]'s `extra_consumed`.

use std::collections::{BTreeMap, BTreeSet};

use anneal_core::{
    Axis, AxisValues, Configuration, Coverage, DebugInfo, ExecMode, Lto, OptLevel, Sanitizer,
};
use anneal_exec::ActionBuilder;

/// A stored renderer: closes over a typed per-axis `fn` and the field extraction the builder
/// method supplied, so by the time it lands here it can only ever read its own axis. Private —
/// rules never construct one directly; they go through the per-axis builder methods.
type StoredRenderer = Box<dyn Fn(&AxisValues) -> Option<String>>;

/// Where a rendered axis flag is routed in the action. A bare routing tag carrying no tool
/// semantics — the framework injects the string, never interprets it — so a rule for any
/// flag-based tool names its own sink (`EnvVar("RUSTFLAGS")`, `EnvVar("CFLAGS")`, …).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlagSink {
    /// Append to an environment variable (space-joined, in declaration order).
    EnvVar(&'static str),
}

/// A rule's map from configuration axes to its inner tool's flags. Built only through the
/// per-axis methods below (e.g. [`lto`](AxisFlagMap::lto)), so each entry's tag, field, and
/// renderer value-type are bound together and cannot be mismatched. The unit is the [`Axis`],
/// so the framework can render flags for a node *and* derive the consumed-axis set from the
/// same source (the module docs explain why that matters).
#[derive(Default)]
pub struct AxisFlagMap {
    entries: Vec<(Axis, FlagSink, StoredRenderer)>,
}

impl AxisFlagMap {
    pub fn empty() -> Self {
        Self::default()
    }

    /// The set of axes this map mentions — the derived consumed set (the flag part).
    pub fn mapped_axes(&self) -> BTreeSet<Axis> {
        self.entries.iter().map(|(axis, _, _)| *axis).collect()
    }

    /// Render every mapped flag for `axes`, grouped per sink (space-joined in declaration
    /// order). Sinks to which no axis currently contributes are absent.
    pub fn lower(&self, axes: &AxisValues) -> AxisLowering {
        let mut env: BTreeMap<&'static str, Vec<String>> = BTreeMap::new();
        for (_, sink, render) in &self.entries {
            if let Some(flag) = render(axes) {
                match sink {
                    FlagSink::EnvVar(var) => env.entry(var).or_default().push(flag),
                }
            }
        }
        AxisLowering {
            env: env
                .into_iter()
                .map(|(var, flags)| (var.to_owned(), flags.join(" ")))
                .collect(),
        }
    }
}

/// Generate one typed builder method per axis. Each binds the [`Axis`] tag, the [`AxisValues`]
/// field, and the renderer's value type together — so a rule cannot tag an entry `Lto` while
/// reading `coverage`, and the renderer (taking the value by itself) cannot read any other
/// axis. Adding an axis is one line here. The list restates the axes from `anneal_core`'s
/// `axis_enum!`, but every part is compile-checked: a wrong field/type/variant won't build,
/// and an omitted axis merely lacks a builder method (it can't be mapped — a safe default).
macro_rules! axis_flag_methods {
    ($($method:ident => ($variant:ident, $value:ty, $field:ident)),+ $(,)?) => {
        impl AxisFlagMap {
            $(
                #[doc = concat!(
                    "Map the `", stringify!($field), "` axis into `sink`. `render` sees only a `",
                    stringify!($value), "` — it cannot read any other axis — and returns the flag \
                     string, or `None` when the value contributes nothing (e.g. a profile default)."
                )]
                pub fn $method(mut self, sink: FlagSink, render: fn($value) -> Option<String>) -> Self {
                    self.entries
                        .push((Axis::$variant, sink, Box::new(move |a: &AxisValues| render(a.$field))));
                    self
                }
            )+
        }
    };
}

axis_flag_methods! {
    opt_level => (OptLevel, OptLevel, opt_level),
    lto => (Lto, Lto, lto),
    debug_info => (DebugInfo, DebugInfo, debug_info),
    sanitizer => (Sanitizer, Sanitizer, sanitizer),
    coverage => (Coverage, Coverage, coverage),
    exec_mode => (ExecMode, ExecMode, exec_mode),
}

/// The concrete per-node result of lowering an [`AxisFlagMap`]: env-var → joined flags.
pub struct AxisLowering {
    pub env: BTreeMap<String, String>,
}

/// Apply a rule's axis mapping to one action and configure it. This is the **sole** place a
/// mapped action's `config` and `consumed_axes` are set: it injects the rendered flags into
/// their sinks, then configures with `config` and a `consumed_axes` set **derived** from the
/// map — its [`mapped_axes`](AxisFlagMap::mapped_axes) plus `extra_consumed` (for
/// output-affecting axes that aren't textual flags, e.g. cargo's `opt_level`). Deriving
/// `consumed` from the same map that produced the flags is what prevents map/consume drift.
///
/// Returns the configured builder (not a finished `Action`) so the caller can still attach a
/// state grant before `try_build`.
pub fn configure_axis_action(
    mut builder: ActionBuilder,
    config: &Configuration,
    map: &AxisFlagMap,
    extra_consumed: &[Axis],
) -> ActionBuilder {
    for (var, value) in map.lower(config.axes()).env {
        if !value.is_empty() {
            builder = builder.env(var, value);
        }
    }
    let mut consumed = map.mapped_axes();
    consumed.extend(extra_consumed.iter().copied());
    builder.configured(config.clone(), consumed)
}
